name: Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # 1️⃣ BUILD CLIENT (React) 
  build-client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["20.x"]

    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Upload client build artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-build
          path: client/dist


  # 2️⃣ BUILD API (Node.js + Express)
  build-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["20.x"]

    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run API tests (optional)
        run: npm test || echo "No tests found"

      - name: Upload API artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-build
          path: api


  # 3️⃣ DOCKER BUILD & PUSH STAGE
  docker:
    runs-on: ubuntu-latest
    needs: [build-client, build-api]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- Build and Push API Image ---
      - name: Build & Push API Image
        uses: docker/build-push-action@v6
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/evento-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/evento-api:${{ github.sha }}

      # --- Build and Push Client Image -
      - name: Build & Push Client Image
        uses: docker/build-push-action@v6
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/evento-client:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/evento-client:${{ github.sha }}

      - name: Verify built images
        run: docker images


        